version: '3.3'

networks:
  redSoftwareSeguro:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "90:80"
    volumes:
      - ./public/:/var/www/html
      - ./ngix/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - bdMysql
    networks:
      - redSoftwareSeguro
      
  php: 
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: php7.4-fpm
    environment:
      DOCUMENT_ROOT: html
    tty: true
    depends_on:
      - bdMysql
    volumes:
      - ./public/:/var/www/html/    
    ports:
      - 9000:80      
    networks:
      - redSoftwareSeguro

  bdMysql:
    image: mysql:latest
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: bdSqlInjection
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysqlROOT}
      MYSQL_DATABASE: ${mysqlBD}
      MYSQL_USER: ${mysqlUSER}
      MYSQL_PASSWORD: ${mysqlPWD}
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./bd/:/docker-entrypoint-initdb.d      
    ports:
      - 3307:3307
    networks:
      - redSoftwareSeguro